/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SnakeImport } from './routes/snake'
import { Route as TicTacToeImport } from './routes/TicTacToe'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SnakeRoute = SnakeImport.update({
  id: '/snake',
  path: '/snake',
  getParentRoute: () => rootRoute,
} as any)

const TicTacToeRoute = TicTacToeImport.update({
  id: '/TicTacToe',
  path: '/TicTacToe',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/TicTacToe': {
      id: '/TicTacToe'
      path: '/TicTacToe'
      fullPath: '/TicTacToe'
      preLoaderRoute: typeof TicTacToeImport
      parentRoute: typeof rootRoute
    }
    '/snake': {
      id: '/snake'
      path: '/snake'
      fullPath: '/snake'
      preLoaderRoute: typeof SnakeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/TicTacToe': typeof TicTacToeRoute
  '/snake': typeof SnakeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/TicTacToe': typeof TicTacToeRoute
  '/snake': typeof SnakeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/TicTacToe': typeof TicTacToeRoute
  '/snake': typeof SnakeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/TicTacToe' | '/snake'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/TicTacToe' | '/snake'
  id: '__root__' | '/' | '/TicTacToe' | '/snake'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TicTacToeRoute: typeof TicTacToeRoute
  SnakeRoute: typeof SnakeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TicTacToeRoute: TicTacToeRoute,
  SnakeRoute: SnakeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/TicTacToe",
        "/snake"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/TicTacToe": {
      "filePath": "TicTacToe.tsx"
    },
    "/snake": {
      "filePath": "snake.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
